-- CONSULTAR QUARQUER UMA DAS 7 TABELAS
SELECT * FROM FUNCIONARIO;
SELECT * FROM CLIENTE;
SELECT * FROM EQUIPAMENTO;
SELECT * FROM ENTREGA;
SELECT * FROM CONTRATO;
SELECT * FROM PEDIDOLOCACAO;
SELECT * FROM ITEMPEDIDO;


-- SERVE PARA VER QUAIS FUNCIONARIOS AGENDARAM AS ENTREGAS EM DETERMINADA DATA
SELECT FUNCIONARIO.NOME_FUNCIONARIO, FUNCIONARIO.CARGO, ENTREGA.DATA_ENTREGA, ENTREGA.RUA
FROM ENTREGA
INNER JOIN FUNCIONARIO ON ENTREGA.COD_FUNCIONARIO = FUNCIONARIO.COD_FUNCIONARIO;

-- SERVE PARA SABER O FUNCIONARIO QUE REDIGIU DETERMINADO CONTRATO E O CLIENTE QUE O ASSINOU
SELECT FUN.NOME_FUNCIONARIO, CLI.NOME_CLIENTE, CON.VALOR, CON.DATA_INICIO, CON.DATA_FIM
FROM CONTRATO CON
INNER JOIN FUNCIONARIO FUN ON CON.COD_FUNCIONARIO = FUN.COD_FUNCIONARIO
INNER JOIN CLIENTE CLI ON CON.COD_CLIENTE = CLI.COD_CLIENTE;

-- QUANTOS EQUIPAMENTOS TEM NO ITEM PEDIDO E O SEU PREÇO POR UNIDADE E EM CONJUNTO
SELECT EQU.NOME_EQUIPAMENTO, EQU.MARCA, EQU.PRECO, ITMP.COD_ITEMPEDIDO, ITMP.QUANTIDADE, ITMP.PRECO_ITEMPEDIDO
FROM ITEMPEDIDO ITMP
INNER JOIN EQUIPAMENTO EQU ON ITMP.COD_EQUIPAMENTO = EQU.COD_EQUIPAMENTO;

--LISTAR TODOS OS FUNCIONARIOS QUE NÃO PODEM FAZER ENTREGA
SELECT NOME_FUNCIONARIO,CARGO
FROM FUNCIONARIO
WHERE FUNCIONARIO.CARGO <> 'Atendente';

--SABER QUANTOS EQUIPAMENTOS TEM EM CADA ITEM PEDIDO, PODENDO NÃO TER NENHUM TAMBEM
SELECT E.NOME_EQUIPAMENTO, E.MARCA, E.ESTADO_CONSERVACAO, E.PRECO, I.QUANTIDADE
FROM EQUIPAMENTO E
LEFT JOIN ITEMPEDIDO I ON E.COD_EQUIPAMENTO = I.COD_EQUIPAMENTO;

-- SABER TODOS OS EQUIPAMENTOS COM ESTADO DE CONSERVAÇÃO EXCELENTE
SELECT NOME_EQUIPAMENTO
FROM EQUIPAMENTO
WHERE ESTADO_CONSERVACAO = 'Excelente';

-- QUANTOS ITENS PEDIDOS TEM EM UM PEDIDO DE LOCACAO
SELECT COD_PEDIDOLOCACAO, COUNT(*)
FROM ITEMPEDIDO
GROUP BY COD_PEDIDOLOCACAO
ORDER BY COD_PEDIDOLOCACAO;

-- QUANTOS EQUIPAMENTOS TEM EM UM PEDIDO DE LOCACAO 
SELECT COD_PEDIDOLOCACAO, SUM(QUANTIDADE)
FROM ITEMPEDIDO
GROUP BY COD_PEDIDOLOCACAO
ORDER BY COD_PEDIDOLOCACAO;

-- QUANTOS EQUIPAMENTOS COM SITUAÇÃO FALSE EXISTE
SELECT NOME_EQUIPAMENTO, COUNT(*)
FROM EQUIPAMENTO
WHERE SITUACAO = FALSE
GROUP BY NOME_EQUIPAMENTO;

-- QUAIS OS PEDIDOS DE LOCAÇÃO QUE TEM MAIS DE 5 ITENS
SELECT COD_PEDIDOLOCACAO, SUM(QUANTIDADE)
FROM ITEMPEDIDO
GROUP BY COD_PEDIDOLOCACAO
HAVING SUM(QUANTIDADE)> 5
ORDER BY COD_PEDIDOLOCACAO;

-- TODOS OS CLIENTES QUE POSSUEM MAIS DE UM CONTRATO
SELECT COD_CLIENTE, COUNT(*)
FROM CONTRATO
GROUP BY COD_CLIENTE
HAVING COUNT(*)>=2;

-- OS CLIENTES QUE NÃO POSSUEM NENHUM CONTRATO
SELECT COD_CLIENTE,NOME_CLIENTE
FROM CLIENTE CL
WHERE NOT EXISTS (SELECT * FROM CONTRATO CO WHERE CO.COD_CLIENTE = CL.COD_CLIENTE);


-- NOME DE TODOS OS EQUIPAMENTOS DE UM PEDIDO DE LOCACAO
SELECT I.COD_PEDIDOLOCACAO, E.NOME_EQUIPAMENTO
FROM ITEMPEDIDO I
JOIN EQUIPAMENTO E ON I.COD_EQUIPAMENTO = E.COD_EQUIPAMENTO;

-- ACHAR TODOS OS FUNCIONARIOS QUE ESTÃO SEM CARGO 
SELECT COD_FUNCIONARIO
FROM FUNCIONARIO
WHERE CARGO = '';