/*
ERRO: TEM ALGUMS ITEMS QUE ESTÃO ALOCADOS (TRUE), MAS NÃO APARECEM EM NENHUM PEDDIDO,
OU SEJA, ESSES NÃO ESTÃO ALUGADOS, MAS CONSTAM COMO SE ESTIVESSEM.

PARA ARRUMAR ISSO FIZ UMA TRANSAÇÃO, PARA TRANSFORMAR TODOS OS QUE 
NÃO ESTVAM EM NENHUM ITEM PEDIDO PARA FALSE
*/ 

BEGIN;
UPDATE EQUIPAMENTO E  SET SITUACAO = FALSE 
WHERE NOT EXISTS (SELECT * FROM ITEMPEDIDO I WHERE I.COD_EQUIPAMENTO = E.COD_EQUIPAMENTO);
-- TODOS OS EQUIOPAMENTOS QUE AINDA NÃO FORAM ALUGADOS
SELECT NOME_EQUIPAMENTO
FROM EQUIPAMENTO
WHERE SITUACAO = FALSE;
COMMIT;






-- TODOS OS VALORES DO ESTADO_CONSERVACAO QUE ESTIVEREM EM BRANCO SERÁ SUBSTITUIDO POR RUIM
BEGIN;
UPDATE EQUIPAMENTO  SET ESTADO_CONSERVACAO = 'Ruim'
WHERE ESTADO_CONSERVACAO = '';
SELECT ESTADO_CONSERVACAO FROM EQUIPAMENTO;
ROLLBACK;





-- ENCERRAR A LOCAÇÃO DO CONTRATO DE CODIGO 4
BEGIN;
--REMOVER ITEM PEDIDO
DELETE FROM ITEMPEDIDO
WHERE COD_PEDIDOLOCACAO = 4;
--DELETAR PEDIDO DE LOCAÇÃO
DELETE FROM PEDIDOLOCACAO
WHERE COD_CONTRATO = 4;
-- DELETAR CONTRATO
DELETE FROM CONTRATO
WHERE COD_CONTRATO = 4;
--SAVE POINT
SAVEPOINT SALVAMENTOITEMPEDIDO;
--COLOCAR OS EQUIPAMENTOS DOS ITEM PEDIDO COMO FALSE
--FIZ UM SIMULAÇÃO DE ERRO, PARA PODER USAR O SAVEPOINT
UPDATE EQUIPAMENTO SET SITUACAO = FALSE
WHERE COD_EQUIPAMENTO IN (9,15);
ROLLBACK TO SALVAMENTOITEMPEDIDO;
--UPDATE REAL AGORA, SEM A SIMULAÇÃO
UPDATE EQUIPAMENTO SET SITUACAO = FALSE
WHERE COD_EQUIPAMENTO IN (6,11);
COMMIT;






--ADICIONAR UMA NOVA LOCAÇÃO
BEGIN;
--INSERIR CONTRATO
INSERT INTO CONTRATO (COD_FUNCIONARIO, COD_CLIENTE, VALOR, DATA_INICIO, DATA_FIM)
VALUES (2,4,340.00,'2024-09-12', '2024-11-12');
--INSERIR PEDIDOLOCACAO
INSERT INTO PedidoLocacao (Cod_Contrato)
VALUES (21);
--INSERIR ENTREGA
INSERT INTO ENTREGA (COD_FUNCIONARIO, DATA_ENTREGA, CEP, RUA, BAIRRO, NUMERO)
VALUES (3,  '2024-09-13', '75340-000', 'Rua Conde de Oriola',         'Jardim Ângela',        5710);
--INSERIR ITEM PEDIDO
INSERT INTO ITEMPEDIDO (COD_EQUIPAMENTO, QUANTIDADE, PRECO_ITEMPEDIDO, COD_PEDIDOLOCACAO, COD_ENTREGA)
VALUES   (4, 1, 340.00,21, 21);
--COLOCAR OS EQUIPAMENTOS DOS ITEM PEDIDO COMO ALUGADOS(TRUE)
UPDATE EQUIPAMENTO SET SITUACAO = TRUE
WHERE COD_EQUIPAMENTO = 4;
ROLLBACK;







--ADICIONANDO 4 NOVOS EQUIPAMENTOS
BEGIN;
INSERT INTO EQUIPAMENTO (NOME_EQUIPAMENTO, SITUACAO, MARCA, ESTADO_CONSERVACAO, PRECO)
VALUES ('Rompedor',       FALSE, 'Bosch',  'Novo', 980.00),
       ('Parafusadeira',  FALSE, 'DeWalt', 'Novo', 190.00),
       ('Policorte',      FALSE, 'Makita', 'Novo', 620.00),
       ('Bomba Submersa', FALSE, 'Famac',  'Novo', 430.00);
COMMIT;





